# SITE CONFIGURATION
baseurl: "/blog"
url: "https://binhonglee.github.io"
title: Blog - BinHong Lee
description: "A personal blog of things I ramble about"


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Blog - BinHong Lee # blog's title
  avatar: assets/logo.png
  favicon: assets/logo.png
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Welcome to a space where I rambles about things~</p>
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: "binhong.lee@asu.edu" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "binhonglee"
  flickr:
  gitlab:
  github: "binhonglee"
  google_plus:
  instagram: "binhonglee"
  keybase:
  linkedin: "https://linkedin.com/in/binhonglee" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "https://stackoverflow.com/users/7461054/binhong" # Full URL
  steam:
  tumblr:
  twitter: "binhonglee" # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: false
  search: true
  tags: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Share+Tech+Mono,Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md"]
