baseURL = "https://binhong.me/blog/"
languageCode = "en-us"
title = "BinHong Lee's Blog"
theme = "my_theme"

[Menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://binhong.me"
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/binhonglee"

[Params]
  favicon = "img/profile.png"
  [Params.author]
    name = "BinHong Lee"
    email = "binhong@binhong.me"
  [Params.social]
    rss = true
    homepage = true
    facebook = "binhonglee"
    github = "binhonglee"
    instagram = "binhonglee"
    linkedin = "binhonglee"
    reddit = "binhonglee"
    stackexchange = "binhonglee"
    twitter = "binhonglee"

[markup.highlight]
  guessSyntax = false
  lineNoStart = 1
  lineNos = true
  style = 'dracula'
  tabWidth = 2
