name: github pages

on:
  push:
    branches:
      - main
      - hugo
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Cache cache directory
        id: cache-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ hashFiles('**/package.json') }}-cache
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ hashFiles('**/package.json') }}-npm-v1
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.8.0"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Serve Hugo in background
        run: hugo serve -D --buildFuture &

      - name: Install npm
        run: npm i

      - name: Generate preview images
        run: npm run build

      - name: Build
        run: hugo --buildFuture

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public