name: github pages

on:
  push:
    branches:
      - main
      - hugo
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ hashFiles('**/package.json') }}-npm
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Serve Hugo in background
        run: hugo serve -D --buildFuture &

      - name: Install npm
        run: npm i

      - name: Generate preview images
        run: npm run build

      - name: Build
        run: hugo --minify --buildFuture

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public